import {
  GenezioDeploy,
  GenezioHttpRequest,
  GenezioHttpResponse,
  GenezioMethod,
} from "@genezio/types";
import { CodeModel } from "../models/code.mjs";
import { connectDb, initTables, syncDb } from "../db/connect.mjs";
import { TrackModel } from "../build/models/track.js";
import { Op } from "sequelize";
import axios from "axios";

export type Track = {
  id: string;
  codeId: string;
  date: Date;
};

const checkUrl = async (url: string) => {
  try {
    const response = await axios.get(url);
    return { url, status: response.status };
  } catch (error: any) {
    if (error.response && error.response.status === 404) {
      return { url, status: 404 };
    } else {
      return { url, status: error.message };
    }
  }
};

@GenezioDeploy()
export class TrackService {
  constructor() {
    this.#connect();
  }

  /**
   * Private method used to connect to the DB.
   */
  #connect() {
    try {
      const db = connectDb();
      initTables(db);
      syncDb(db);
    } catch (err) {
      console.log(
        "\x1b[33m%s\x1b[0m",
        "WARNING: Check if your environment variables are correctly set"
      );
      console.error(err);
    }
  }

  @GenezioMethod({ type: "cron", cronString: "0 0 * * *" })
  async logNotFoundUrls() {
    const codes = await CodeModel.findAll();
    const urls = codes.map((code) => code.url);
    const promises = urls.map((url) => checkUrl(url));
    const results = await Promise.all(promises);
    const notFoundUrls = results.filter((result) => result.status === 404);
    console.log("Not found urls", notFoundUrls);
  }

  async getTrackingData(codeId: string): Promise<Track[]> {
    const dateNow = new Date();
    const startOfDay = new Date(dateNow.setHours(0, 0, 0, 0));
    const endOfDay = new Date(dateNow.setHours(23, 59, 59, 999));

    const res = await TrackModel.findAll({
      where: {
        codeId: codeId,
        date: {
          [Op.and]: {
            [Op.gte]: startOfDay,
            [Op.lte]: endOfDay,
          },
        },
      },
    }).catch((error) => {
      console.log(error);
      return null;
    });
    if (!res) {
      throw new Error("Error getting tracking data");
    }
    return res;
  }

  /**
   * Http method that tracks a code.
   * All qr codes generated by this service will redirect to this endpoint.
   * This method will then redirect the user to the original url.
   *
   * @param {*} req The http request object.
   * @returns An object containing the statusCode, body and headers.
   */
  @GenezioMethod({ type: "http" })
  async trackCode(req: GenezioHttpRequest): Promise<GenezioHttpResponse> {
    if (!req.queryStringParameters || !req.queryStringParameters.codeId) {
      return {
        statusCode: "400",
        body: "Missing codeId parameter in the request",
      };
    }
    const codeId = req.queryStringParameters.codeId;
    console.log(`Tracking code with id ${codeId}`);
    const code = await CodeModel.findOne({ where: { id: codeId } });
    if (!code) {
      return {
        statusCode: "404",
        body: "Code not found",
      };
    }
    const res = await TrackModel.create({
      codeId: codeId,
      date: new Date(),
    }).catch((error) => {
      console.log(error);
      return null;
    });
    if (!res) {
      console.log("Error tracking code");
    }

    return {
      statusCode: "303",
      body: "Code tracked successfully",
      headers: {
        Location: code.url,
      },
    };
  }
}
